name: BuildContainer

on: 
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-and-deploy-app:
    name: BuildAndDeployApp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: BuildAndPushToDocker image
        uses: docker/build-push-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
          repository: lupitia1/MyPortfolio
          tags: latest

      